language: cpp
compiler: gcc
dist: trusty
os: windows

script: 
  # Build and run this project
  - g++ -std=c++17 -O0 -Wall -Wextra -g  -Iinclude -o output\main.exe src/cell.o src/display.o src/main.o src/population.o -lfreeglut -lopengl32 -lglu32 -Llib
